/* Run inside the isolated forum's network namespace. See test/README.md. */
const assert = require("node:assert/strict");
const fs = require("node:fs");
const { chromium } = require(process.env.RSC_PLAYWRIGHT || "playwright");
(async () => {
  const credentials = JSON.parse(fs.readFileSync(process.env.RSC_BROWSER_CREDENTIALS || "/tmp/rsc-browser-key.json", "utf8"));
  const browser = await chromium.launch({ executablePath: process.env.RSC_CHROMIUM, args: ["--no-sandbox", "--host-resolver-rules=MAP rsc.test 127.0.0.1", "--unsafely-treat-insecure-origin-as-secure=http://rsc.test:3000"] });
  const context = await browser.newContext({ viewport: { width: 1440, height: 1000 }, locale: "zh-CN" });
  const page = await context.newPage();
  const errors = [];
  const legacyRequests = [];
  const quoteRefreshes = [];
  page.on("response", response => {
    if (/\/rsc\/instruments\/\d+\/refresh\.json/.test(response.url())) {
      quoteRefreshes.push({ status: response.status(), method: response.request().method() });
    }
  });
  page.on("request", request => { if (request.url().includes("/app-rsc-api")) { legacyRequests.push(request.url()); } });
  page.on("pageerror", error => errors.push(error.message));
  page.on("console", msg => { if (msg.type() === "error") { console.log("console:", msg.text().slice(0, 600)); } });
  page.on("response", response => { if (response.status() >= 400) { console.log("http:", response.status(), response.url()); } });
  const output = process.env.RSC_BROWSER_OUTPUT || "/tmp/rsc-browser";
  fs.mkdirSync(output, { recursive: true });
  async function capture(name) {
    await page.evaluate(() => window.scrollTo({ top: 0, behavior: "instant" }));
    await page.evaluate(() => new Promise(resolve => requestAnimationFrame(() => requestAnimationFrame(resolve))));
    await page.screenshot({ path: `${output}/${name}.png`, fullPage: true });
  }
  try {
    await page.goto("http://rsc.test:3000/", { waitUntil: "domcontentloaded" });
    await page.locator("#main-outlet").waitFor();
    const login = await page.evaluate(async ({ username, password }) => {
      const csrf = await (await fetch("/session/csrf.json")).json();
      const response = await fetch("/session.json", { method: "POST", headers: { "Content-Type": "application/json", "X-CSRF-Token": csrf.csrf, "X-Requested-With": "XMLHttpRequest" }, body: JSON.stringify({ login: username, password }) });
      return { status: response.status, body: await response.text() };
    }, credentials);
    assert.equal(login.status, 200, login.body);
    assert.ok(!JSON.parse(login.body).error, login.body);
    if (!process.env.RSC_BROWSER_ADMIN_ONLY) {
    await page.goto("http://rsc.test:3000/rsc", { waitUntil: "domcontentloaded" });
    await page.locator(".rsc-app").waitFor({ timeout: 30000 });
    console.log("Native wallet rendered");
    await capture("wallet-desktop");
    await page.locator(".rsc-wallet-history").getByRole("cell", { name: /管理员发放/ }).first().waitFor();
    await page.getByLabel("接收人用户名").fill("rsc_bob");
    await page.getByLabel("金额（RSC）", { exact: true }).fill("1.25");
    await page.getByRole("button", { name: "转账", exact: true }).click();
    await page.getByRole("status").filter({ hasText: "操作成功" }).waitFor();
    await page.getByRole("button", { name: "发红包", exact: true }).click();
    await page.getByRole("button", { name: "收回剩余红包", exact: true }).waitFor();
    const packets = await page.evaluate(async () => (await (await fetch("/rsc/state.json")).json()).packets);
    const sharedToken = packets.find((p) => p.own && p.status === "open").token;
    const guestContext = await browser.newContext({ locale: "zh-CN" });
    const guest = await guestContext.newPage();
    await guest.goto(`http://rsc.test:3000/rsc/packets/${sharedToken}`);
    await guest.locator(".rsc-public-packet").waitFor();
    await guest.getByRole("link", { name: "登录领取", exact: true }).waitFor();
    assert.ok(!(await guest.locator("body").innerText()).includes("访问被拒绝"));
    await guestContext.close();
    console.log("Guest packet preview works without wallet membership or private state");
    await page.getByRole("button", { name: "收回剩余红包", exact: true }).click();
    await page.getByText("已收回", { exact: false }).waitFor();
    console.log("Native packet created and remainder refunded");
    await page.locator(".rsc-packet-nav a").click();
    await page.locator(".rsc-tabs").getByRole("link", { name: "股市", exact: true }).click();
    const board = page.locator(".rsc-market-board");
    await board.getByRole("button", { name: "DEMO-A", exact: true }).waitFor();
    await board.getByRole("button", { name: "全部", exact: true }).click();
    assert.equal(await board.locator(".rsc-quote-row").count(), 12);
    assert.ok(await board.getByRole("button", { name: "下一页", exact: true }).isDisabled());
    await board.getByRole("button", { name: "DEMO-L", exact: true }).click();
    assert.ok(await page.getByRole("button", { name: "提交委托", exact: true }).isDisabled(), "Stale quotes disable submission");
    assert.equal(await page.locator(".rsc-change-pill").innerText(), "—", "Missing previous close must not invent daily change");
    await board.getByRole("button", { name: "虚拟币", exact: true }).click();
    assert.equal(await board.locator(".rsc-quote-row").count(), 2);
    await board.getByRole("button", { name: "全部", exact: true }).click();
    await board.getByRole("searchbox").fill("星海");
    assert.equal(await board.locator(".rsc-quote-row").count(), 1);
    await board.getByRole("button", { name: "DEMO-E", exact: true }).click();
    assert.ok((await page.locator(".rsc-detail-heading").innerText()).includes("星海"));
    await board.getByRole("searchbox").fill("not-a-symbol");
    await board.getByText("没有匹配的标的", { exact: true }).waitFor();
    await board.getByRole("searchbox").fill("");
    await board.getByLabel("行情排序").selectOption("gainers");
    assert.equal(await board.locator(".rsc-quote-row").first().getAttribute("aria-label"), "DEMO-E");
    await board.getByLabel("行情排序").selectOption("symbol");
    await board.getByRole("button", { name: "DEMO-A", exact: true }).click();
    const firstItem = board.locator(".rsc-quote-item").filter({ has: page.getByRole("button", { name: "DEMO-A", exact: true }) });
    await firstItem.getByRole("button", { name: "做空", exact: true }).click();
    assert.equal(await page.locator(".rsc-order-ticket select").first().inputValue(), "short");
    await firstItem.getByRole("button", { name: "做多", exact: true }).click();
    console.log("Market categories, search, pagination, sorting, selection, quick trade and stale quotes passed");
    await page.locator(".rsc-chart svg polyline").waitFor();
    assert.ok((await page.locator(".rsc-chart polyline").getAttribute("points")).length > 100);
    const originalPoints = await page.locator(".rsc-history polyline").getAttribute("points");
    await page.getByRole("button", { name: "放大", exact: true }).click();
    assert.notEqual(await page.locator(".rsc-history polyline").getAttribute("points"), originalPoints);
    await page.getByRole("button", { name: "更早行情", exact: true }).click();
    await page.getByRole("button", { name: "重置视图", exact: true }).click();
    assert.equal(await page.locator(".rsc-history polyline").getAttribute("points"), originalPoints);
    await page.getByLabel("杠杆倍数", { exact: true }).fill("5");
    await page.getByRole("button", { name: "提交委托", exact: true }).click();
    await page.getByRole("status").filter({ hasText: "操作成功" }).waitFor();
    await page.locator(".rsc-position").waitFor({ timeout: 65000 });
    console.log("Native stock order filled and position displayed");
    if (process.env.RSC_BROWSER_REFRESH_QUOTES === "1") {
      assert(quoteRefreshes.some((response) => response.method === "POST" && response.status === 200), "Selecting an instrument requests its current quote through the native endpoint");
      assert(quoteRefreshes.length < 20, "Rapid selection coalesces refreshes instead of flooding the endpoint");
      console.log("Selected instrument quote refresh completed through native POST endpoint");
    }
    await page.getByRole("button", { name: "五天", exact: true }).click();
    await page.getByRole("button", { name: "折线 / K 线", exact: true }).click();
    await page.locator(".rsc-history svg rect").first().waitFor();
    await page.getByRole("button", { name: "折线 / K 线", exact: true }).click();
    await page.locator(".rsc-position-details summary").click();
    await page.locator(".rsc-position").getByLabel("追加保证金", { exact: true }).fill("5");
    await page.locator(".rsc-position").getByRole("button", { name: "追加保证金", exact: true }).click();
    await page.getByRole("status").filter({ hasText: "操作成功" }).waitFor();
    await page.locator(".rsc-tabs").getByRole("link", { name: "排行榜", exact: true }).click();
    await page.getByRole("heading", { name: "排行榜", exact: true }).waitFor();
    await page.getByRole("cell", { name: "rsc_alice", exact: true }).waitFor();
    await page.getByRole("button", { name: "rsc_alice", exact: true }).click();
    await page.locator(".rsc-trader-detail").waitFor();
    await page.locator(".rsc-trader-detail").getByRole("button", { name: "委托记录", exact: true }).click();
    await page.locator(".rsc-trader-detail").getByRole("cell", { name: "DEMO-A", exact: true }).waitFor();
    assert.equal(await page.locator('.rsc-tabs').count(), 1);
    assert.equal(await page.locator('.rsc-tabs a.active').innerText(), '排行榜');
    assert.equal(await page.locator('.rsc-tabs a[href="/rsc/admin"]').count(), 0);
    await page.locator('.rsc-tabs').getByRole('link', { name: '股市', exact: true }).click();
    await page.locator('.rsc-trading-summary').waitFor();
    await page.locator('.rsc-tabs').getByRole('link', { name: '排行榜', exact: true }).click();
    await page.getByRole('heading', { name: '排行榜', exact: true }).waitFor();
    await capture("leaderboard-desktop");
    await page.locator(".rsc-tabs").getByRole("link", { name: "股市", exact: true }).click();
    await page.locator(".rsc-position").waitFor();
    await capture("market-desktop");
    await page.locator("#toggle-current-user").click();
    const notification = page.locator('a[href^="/rsc/market?instrument_id="]').filter({ hasText: "委托已成交" }).first();
    await notification.waitFor();
    await capture("notifications-desktop");
    await notification.click();
    await page.waitForURL(/instrument_id=.*order_id=/);
    assert.ok((await page.locator(".rsc-detail-heading").innerText()).includes("DEMO-A"));
    const orderId = new URL(page.url()).searchParams.get("order_id");
    await page.locator(`#rsc-order-${orderId}`).waitFor();
    console.log("Native stock notification navigated to its instrument and exact order");
    await page.locator(".rsc-tabs").getByRole("link", { name: "赛事预测", exact: true }).click();
    await page.locator(".rsc-match").first().waitFor();
    await page.locator(".rsc-match").filter({ hasText: "河畔联队" }).getByRole("button", { name: /提交预测|修改预测/ }).click();
    await page.getByRole("status").filter({ hasText: "操作成功" }).waitFor();
    await capture("sports-desktop");
    await page.setViewportSize({ width: 390, height: 844 });
    await capture("sports-mobile");
    assert.ok(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth + 1), "Sports page must not overflow on mobile");
    await page.locator(".rsc-tabs").getByRole("link", { name: "股市", exact: true }).click();
    await page.locator(".rsc-market-board").waitFor();
    assert.ok(!await page.locator(".rsc-chart").isVisible(), "Mobile starts with the list");
    await capture("market-mobile");
    await page.locator(".rsc-market-board").getByRole("button", { name: "DEMO-B", exact: true }).click();
    await page.locator(".rsc-chart").waitFor();
    await capture("market-detail-mobile");
    await page.getByRole("button", { name: "返回行情列表", exact: false }).click();
    await page.locator(".rsc-market-board").waitFor();
    console.log("Mobile list, detail and return navigation passed");
    assert.ok(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth + 1), "Market page must not overflow on mobile");
    await require("./mobile-layout.cjs")(page, output);
    await page.goto(`http://rsc.test:3000${credentials.topic_path}`, { waitUntil: "domcontentloaded" });
    await page.locator(".rsc-tip-button").first().waitFor();
    assert.equal(await page.locator(".rsc-tip-button").count(), 1);
    assert.equal(await page.locator(".post-action-menu__reward").count(), 0);
    await page.locator(".rsc-tip-button").first().click();
    await page.locator(".rsc-tip-modal input").fill("1.50");
    await page.locator(".rsc-tip-modal").getByRole("button", { name: "帖子打赏", exact: true }).click();
    await page.locator(".rsc-tip-modal").waitFor({ state: "detached" });
    await page.locator(".rsc-post-tips").first().waitFor();
    assert.ok((await page.locator(".rsc-post-tips").first().innerText()).includes("1.5"));
    await capture("post-tips-mobile");
    assert.deepEqual(legacyRequests, [], "Native mode must not call legacy JWT or tip endpoints");
    console.log("Standalone native post tip and live summary completed without legacy API calls");
    const denied = await page.evaluate(async () => (await fetch("/rsc/admin/state.json")).status);
    assert.equal(denied, 403, "Non-admin API access is denied");
    }
    await context.clearCookies();
    await page.goto("http://rsc.test:3000/", { waitUntil: "domcontentloaded" });
    await page.locator("#main-outlet").waitFor();
    const adminLogin = await page.evaluate(async ({ username, password }) => {
      const csrf = await (await fetch("/session/csrf.json")).json();
      const response = await fetch("/session.json", { method: "POST", headers: { "Content-Type": "application/json", "X-CSRF-Token": csrf.csrf, "X-Requested-With": "XMLHttpRequest" }, body: JSON.stringify({ login: username, password }) });
      return { status: response.status, body: await response.text() };
    }, credentials.admin);
    assert.equal(adminLogin.status, 200, adminLogin.body);
    assert.ok(!JSON.parse(adminLogin.body).error, adminLogin.body);
    await page.setViewportSize({ width: 1440, height: 1000 });
    await page.goto("http://rsc.test:3000/rsc/admin");
    await page.getByRole("heading", { name: "RSC 管理", exact: true }).waitFor();
    assert.equal(await page.locator('.rsc-tabs a.active').innerText(), 'RSC 管理');
    assert.ok(!(await page.locator("body").innerText()).includes("discourse.application-show-footer"), "Plugin uses the current footer API");
    await page.getByLabel("项目", { exact: true }).selectOption("instrument");
    await page.getByLabel("标的代码", { exact: true }).fill("NATIVE-TEST");
    await page.getByLabel("名称", { exact: true }).fill("原生后台测试标的");
    await page.getByLabel("数据源代码", { exact: true }).fill("TEST");
    await page.getByLabel("报价币种", { exact: true }).fill("USD");
    await page.getByLabel("最小数量", { exact: true }).fill("1");
    await page.getByLabel("数量步长", { exact: true }).fill("1");
    await page.getByLabel("手续费（基点）", { exact: true }).fill("5");
    await page.getByLabel("操作原因", { exact: true }).fill("隔离浏览器验收");
    await page.getByRole("button", { name: "保存", exact: true }).click();
    await page.getByRole("status").filter({ hasText: "操作成功" }).waitFor();
    await page.getByRole("cell", { name: "NATIVE-TEST", exact: true }).waitFor();
    const activity = page.locator(".rsc-admin-tools");
    await activity.getByLabel("资金类型", { exact: true }).selectOption("post_tip");
    await activity.getByRole("button", { name: "查询资金记录", exact: true }).click();
    await activity.getByRole("cell", { name: "rsc_bob", exact: true }).waitFor();
    await page.getByRole("button", { name: "查看搜索需求统计", exact: true }).click();
    await page.locator(".rsc-admin-approval table").waitFor();
    await page.getByRole("button", { name: "立即检查并结算", exact: true }).click();
    await page.getByRole("status").filter({ hasText: "已结算" }).first().waitFor();
    await capture("admin-desktop");
    await page.setViewportSize({ width: 390, height: 844 });
    assert.ok(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth + 1), "Admin page must not overflow on mobile");
    await capture("admin-mobile");
    console.log("Native admin permission gate, form, audit and responsive layout passed");
    assert.deepEqual(errors, [], "No browser runtime errors");
    console.log(process.env.RSC_BROWSER_ADMIN_ONLY ? "PASS native admin form, audit, responsive layout and runtime checks" : "PASS native pages, SPA navigation, chart, transfer, packet refund, stock fill, notifications, prediction, tip, admin, mobile overflow and runtime checks");
  } catch (error) {
    await capture("failure");
    console.log("PAGE:", (await page.locator("body").innerText()).slice(0, 4000));
    console.log("ERRORS:", errors);
    throw error;
  } finally { await browser.close(); }
})().catch(error => { console.error(error); process.exitCode = 1; });
