import assert from 'node:assert/strict';
import fs from 'node:fs';
const source = fs.readFileSync(new URL('../assets/javascripts/discourse/lib/rsc-performance.js', import.meta.url), 'utf8');
const { performanceChart } = await import(`data:text/javascript;base64,${Buffer.from(source).toString('base64')}`);
const now = Date.parse('2026-09-22T12:00:00Z');
const point = (days, value) => ({at: new Date(now - days * 86400000).toISOString(), return_pct: value});
const rows = [point(40,'0'), point(20,'2'), point(6,'4'), point(2,'8'), point(1,'10')];
assert.equal(performanceChart(rows, 3, now).segments[0].split(' ').length, 2);
assert.equal(performanceChart(rows, 7, now).segments[0].split(' ').length, 3);
assert.equal(performanceChart(rows, 30, now).segments[0].split(' ').length, 4);
assert.equal(performanceChart(rows, 0, now).segments[0].split(' ').length, 5);
assert.equal(performanceChart(rows, 3, now).last, 10, 'Range retains cumulative returns');
assert.equal(performanceChart([point(40,'0'),point(20,'2')],7,now),null, 'No invented recent data');
assert.equal(performanceChart([point(1,'1')],0,now),null);
assert.equal(performanceChart(undefined,0,now),null);
const gap = performanceChart([point(7,'1'),point(6,'2'),point(5,null),point(4,'3'),point(3,'4')],0,now);
assert.equal(gap.segments.length,2, 'Unknown return must break the line');
assert.equal(performanceChart([point(2,'0'),point(1,'0')],0,now).segments[0], '12,80 588,80');
assert.equal(performanceChart([point(1,'1'),point(-1,'2')],0,now),null,'No future points');
console.log('PASS performance ranges, gaps, sparse data, cumulative values and flat series');
